# Cloud Build の設定ファイル
# 実行コマンド: gcloud builds submit --config cloudbuild.yaml

steps:
  # ステップ1: Dockerイメージをビルドします。
  # 'bash -c' を使うことで、$$VAR 構文で環境変数を安全に展開し、'INVALID_ARGUMENT'エラーを解決します。
  # イメージタグには、ローカルからのデプロイでも有効な 'latest' を使用します。
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          -t us-west1-docker.pkg.dev/$PROJECT_ID/my-app-repo/${_SERVICE_NAME}:latest \
          --build-arg="FIREBASE_API_KEY=$$FIREBASE_API_KEY_SECRET" \
          --build-arg="FIREBASE_AUTH_DOMAIN=$$FIREBASE_AUTH_DOMAIN_SECRET" \
          --build-arg="FIREBASE_PROJECT_ID=$$FIREBASE_PROJECT_ID_SECRET" \
          --build-arg="FIREBASE_STORAGE_BUCKET=$$FIREBASE_STORAGE_BUCKET_SECRET" \
          --build-arg="FIREBASE_MESSAGING_SENDER_ID=$$FIREBASE_MESSAGING_SENDER_ID_SECRET" \
          --build-arg="FIREBASE_APP_ID=$$FIREBASE_APP_ID_SECRET" \
          --build-arg="ADMIN_EMAIL=$$ADMIN_EMAIL_SECRET" \
          .
    secretEnv:
      - 'FIREBASE_API_KEY_SECRET'
      - 'FIREBASE_AUTH_DOMAIN_SECRET'
      - 'FIREBASE_PROJECT_ID_SECRET'
      - 'FIREBASE_STORAGE_BUCKET_SECRET'
      - 'FIREBASE_MESSAGING_SENDER_ID_SECRET'
      - 'FIREBASE_APP_ID_SECRET'
      - 'ADMIN_EMAIL_SECRET'

  # ステップ2: ビルドしたイメージをArtifact Registryにプッシュします。
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-west1-docker.pkg.dev/$PROJECT_ID/my-app-repo/${_SERVICE_NAME}:latest']

  # ステップ3: ビルドしたイメージをCloud Runにデプロイします。
  # ★★★ 重要 ★★★
  # ここで、サーバーサイド専用のAPI_KEYを安全な「実行時」環境変数として設定します。
  # このキーはビルドには一切含まれず、コンテナイメージの中にも残りません。
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${_SERVICE_NAME}'
      - '--image=us-west1-docker.pkg.dev/$PROJECT_ID/my-app-repo/${_SERVICE_NAME}:latest'
      - '--region=us-west1'
      - '--platform=managed'
      - '--allow-unauthenticated' # サービスを公開する場合に設定
      - '--set-secrets=API_KEY=API_KEY:latest,FIREBASE_PROJECT_ID=ADMIN_FIREBASE_PROJECT_ID:latest,FIREBASE_CLIENT_EMAIL=FIREBASE_CLIENT_EMAIL:latest,FIREBASE_PRIVATE_KEY=FIREBASE_PRIVATE_KEY:latest,SITE_BASE_URL=SITE_BASE_URL:latest' # 実行時にGemini APIキーを環境変数として設定
    secretEnv: ['API_KEY_SECRET','ADMIN_FIREBASE_PROJECT_ID_SECRET','FIREBASE_CLIENT_EMAIL_SECRET','FIREBASE_PRIVATE_KEY_SECRET','SITE_BASE_URL_SECRET'] # この行を追加してエラーを解決

# ビルドが生成する最終的なイメージ
images:
  - 'us-west1-docker.pkg.dev/$PROJECT_ID/my-app-repo/${_SERVICE_NAME}:latest'

# ビルドプロセス中に利用可能にするSecret Managerのシークレット
availableSecrets:
  secretManager:
    # この`gemini-api-key`は、ステップ3のデプロイコマンドでのみ使用されます
    - versionName: projects/$PROJECT_ID/secrets/API_KEY/versions/latest
      env: 'API_KEY_SECRET' # This is used by the gcloud deploy step, NOT the build step.
    - versionName: projects/$PROJECT_ID/secrets/ADMIN_FIREBASE_PROJECT_ID/versions/latest
      env: 'ADMIN_FIREBASE_PROJECT_ID_SECRET' # This is used by the gcloud deploy step, NOT the build step.
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_CLIENT_EMAIL/versions/latest
      env: 'FIREBASE_CLIENT_EMAIL_SECRET' # This is used by the gcloud deploy step, NOT the build step.
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_PRIVATE_KEY/versions/latest
      env: 'FIREBASE_PRIVATE_KEY_SECRET' # This is used by the gcloud deploy step, NOT the build step.
    - versionName: projects/$PROJECT_ID/secrets/SITE_BASE_URL/versions/latest
      env: 'SITE_BASE_URL_SECRET' # This is used by the gcloud deploy step, NOT the build step.
    # 以下の変数は、ステップ1のビルドコマンドで使用されます
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_API_KEY/versions/latest
      env: 'FIREBASE_API_KEY_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_AUTH_DOMAIN/versions/latest
      env: 'FIREBASE_AUTH_DOMAIN_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_PROJECT_ID/versions/latest
      env: 'FIREBASE_PROJECT_ID_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_STORAGE_BUCKET/versions/latest
      env: 'FIREBASE_STORAGE_BUCKET_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_MESSAGING_SENDER_ID/versions/latest
      env: 'FIREBASE_MESSAGING_SENDER_ID_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/FIREBASE_APP_ID/versions/latest
      env: 'FIREBASE_APP_ID_SECRET'
    - versionName: projects/$PROJECT_ID/secrets/ADMIN_EMAIL/versions/latest
      env: 'ADMIN_EMAIL_SECRET'

# 置換可能な変数
substitutions:
  _SERVICE_NAME: 'kashikoi-mama-note' # Cloud Runのサービス名（任意に変更可能）